"""add anomaly detection fields to queries

Revision ID: 43c833ef8627
Revises: 145f789d7f02
Create Date: 2026-08-10 20:22:05.058619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c833ef8627'
down_revision: Union[str, Sequence[str], None] = '145f789d7f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('anomaly_model_used', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('anomaly_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'anomaly_count')
    op.drop_column('queries', 'anomaly_model_used')
    # ### end Alembic commands ###
