"""add chart config, chart image, explanation to queries

Revision ID: b82cc3ca79f6
Revises: cd6a0b8d0d44
Create Date: 2026-08-09 23:07:32.309536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82cc3ca79f6'
down_revision: Union[str, Sequence[str], None] = 'cd6a0b8d0d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('chart_config', sa.JSON(), nullable=True))
    op.add_column('queries', sa.Column('chart_image_path', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'explanation')
    op.drop_column('queries', 'chart_image_path')
    op.drop_column('queries', 'chart_config')
    # ### end Alembic commands ###
