"""add forecasting fields to queries

Revision ID: bd119bce8031
Revises: b82cc3ca79f6
Create Date: 2026-08-10 14:03:33.623227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd119bce8031'
down_revision: Union[str, Sequence[str], None] = 'b82cc3ca79f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('forecast_model_used', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('forecast_predictions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'forecast_predictions')
    op.drop_column('queries', 'forecast_model_used')
    # ### end Alembic commands ###
